### ISSUE TITLE
For all Stories we have Categories

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#10]
Later we can add Skills but for now we can add:

- Trainer/Mentor/Participant
- `<Region>`
- `<Hub>`

**Comment by timmwille** [comment]
I think it is ok if we have:
- `<Country>`
- `<Region>`



And in case we add the hubs, we might go for:
- `Hub` or  `Member` ?

**Comment by bmen** [comment]
https://github.com/ASKnet-Community/LEAD/issues/1
