### ISSUE TITLE
check the right license

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#13]

**Comment by timmwille** [comment]
I think we have to link in the README.md to the used theme LICENSE.txt or Source/Orininator
https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/blob/Pintereso-Theme/LICENSE.txt
Same counts for the original Repository that @gibertgibs started with :)


and then I would give the whole project a CC-BY or a MIT License → of course we could also use a CC-BY-SA License but might hold more restrictions then we need, as this is a very specific content.

@gibertgibs what do you think should it be a permissive license as MIT to just reference back to us and all Contributors or shall we give it a stronger License like CC-BY-SA to force everyone to keep it open under a compatible Share-Alike (SA) License?

**Comment by bmen** [comment]
https://github.com/ASKnet-Community/LEAD/issues/3
