### ISSUE TITLE
Uncompleted Stories Checklist

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#17]

**Comment by timmwille** [comment]
by the way, if you check the "_posts" folder there are the stories (currently the date is the day number of the story, but we could check if it works with simple numbers as well) 

And if you check out the "raw" md code it is very straight forward to edit:
https://raw.githubusercontent.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Pintereso-Theme/_posts/2020-07-01-Gilbert-Charles.md

```
---
title:  "Gilbert Charles"
metadate: "hide"
categories: [ Participant, Github ]
image: "/assets/images/gilbert.jpg"
---
```

I suggest the following:
- image: `"assets/images/<name-#>/<name-01>.jpg"`

- categories: [` <Participant/Trainer/Mentor>, <Region>, <Hub> ]`

**Comment by timmwille** [comment]
so whos pictures are we missing/whos pictures do we have?

**Comment by timmwille** [comment]
https://search.creativecommons.org/photos/0a8e21ee-c13a-43f1-86cb-50fc46236158

**Comment by gibertgibs** [comment]
I think we need to approach each member directly for their stories....Or we sit the whole year waiting for some to add...who knows a few might still be facing challenges adding stories but find it hard to ask.

**Comment by chardso** [comment]
But if I can rem we wrote stories in the begining ,BT to me it is better we write new ones coz by then,some of us didn't know #ASKnet well,well ooh!

**Comment by timmwille** [comment]
> by the way, if you check the "_posts" folder there are the stories (currently the date is the day number of the story, but we could check if it works with simple numbers as well)
> 
> And if you check out the "raw" md code it is very straight forward to edit: https://raw.githubusercontent.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Pintereso-Theme/_posts/2020-07-01-Gilbert-Charles.md
> 
> ```
> ---
> title:  "Gilbert Charles"
> metadate: "hide"
> categories: [ Participant, Github ]
> image: "/assets/images/gilbert.jpg"
> ---
> ```
> 
> I suggest the following:
> 
>     * image: `"assets/images/<name-#>/<name-01>.jpg"`
> 
>     * categories: [` <Participant/Trainer/Mentor>, <Region>, <Hub> ]`

@bmen maybe we could go for this picture logic? also connected to #45

**Comment by bmen** [comment]
It could be it works with numbers instead of dates.

I don't know exactly what you mean by picture logic. Currently the images have the following path:

/assets/images/<Name of the participant>/<Name of the participant>-<x+1>.jpg

**Comment by MartinSchott** [comment]
please continue discussion here: https://github.com/ASKnet-Community/LEAD/issues/6
