### ISSUE TITLE
MEMBERS ARE URGED TO ADD THEIR STORIES TO THE FILES.

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#2]
Please if you know that you have not yet added your own part of the stories, please let's comply and add the stories to the files with our names....
It's only Our mentor Richard and Baby Omer whose names have no files but will add them soon.

**Comment by timmwille** [comment]
Hey @gibertgibs check out my story merge request #5 :smiley:
