### ISSUE TITLE
Kenyi Gilbert Charles.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#21]

**Comment by gibertgibs** [comment]
---
title:  "Gilbert Charles"
metadate: "hide"
categories: [ Participant, Github ]
image: "/assets/images/gilbert.jpg"
---

# GILBERT'S STORY

![](/pictures/Gilbert2.jpg)

Hello friends and Community Members,
I am Gilbert Charles by names but also friends call me Kane, shortened out from the name Kenyi as It's my birth name. 
I am an enthusiastic South Sudanese born in a small Refugee Settlement named Robidire in Adjumani District on 30th November 1998.
Life was good in the beginning with both parents by my  side and everything seemed so beautiful, but then as time went on, I realized I was just a kid by then to know
what really life was. As years past on I came to know I wasn't a citizen of the country I was in, but then as a child I had a lot of questions to ask because I wanted to know what
really happened in the past years before I was born that brought about the taking of refuge in Robidire, Adjumani, Uganda.
As life went on I started to learn and hear from my grand parents how they ran into Uganda and how many suffered, the pains they feel as the memories of their lost ones during the war crosses by.
And when 2008 came, Of course repatriation took place, as it was my first time to step in my fatherland South Sudan, Imagining the sweetness of life and love from the natives.
Enjoyed the moments with the family, Of course Boom 2016 comes and I get myself back in Pagirinya Refugee Settlement in Adjumani. What could I say, didn't know the source of the crisis, 
and yeah no power to stop but only had to put down this set of piece to my dear fellow South Sudan seriously.
The piece I titled "LETTER TO THE SOUTH SUDAN SERIOUSLY" 


## **LETTER TO THE SOUTH SUDANESE**

*Trauma breaks mine heart
The suffering of my people shutters me
The demolition of the Great motherland sharply instills pain in mine heart,
The harmony; The love; The blessings of our for fathers devoured and turned into the hatred; the segregation and tribalism by a twist inflicting crisis.*

*How long shall we remain Refugees?
When shall we feel the peace of our fatherland?
Broken is mine heart,
I'm torn between tolerance to pain and acceptance to death,
Dear fellow South Sudanese,
I was in quietude merely sweethearted
A cup of poison given to me to set me free in place of a pond of peace,
I was plagued with undue melancholy of the shame of being in quietude,
Let's arise.*

*My grandparents came into exile as Refugees,
My parents gave birth to me in exile as a Refugee,
For how long should the generation remain I exile as Refugees:
Warib cing wa me ryemo cen man kare acel;
Cause no one is born hating someone,
Together we can our fatherland South Sudan;
Ma badna anihina, bi geheru beledna Junub Al Sudan,
Let's unite to eradicate tribalism to feel the presence of peace;
Ti yi tomorgi 'borik i togbwo'ja na gebeliya a'nyen yi kurundo 'busan na taling,
Together as a Nation;
Together as South Sudan
Egbwe Kolu a'a 
Bukku panda yiek nhial
Love without discrimination
Happy South Sudan.*

### Peace4SouthSudan

The piece above expressed the pain I have deep inside my heart for what is happening to Our country South Sudan, Inspite of what is happening to my Country
South Sudan, I still believe and will always believe that we can all still collect the remaining pieces of our bodies, enrich ourselves and learn to move with a positive hope of transformation.
Besides transformation, technology has knocked on my door, all I need to do is concentrate.

**Comment by gibertgibs** [comment]
A new story is loading..So this will not be added to the webpage.

**Comment by bmen** [comment]
I have updated your profile: https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Gilbert-Charles/

**Comment by MartinSchott** [comment]
I've checked all the content, looks like the content in your issue is different from the one currently on your [profile](
https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Gilbert-Charles/). 
Is this on purpose? Can you create a merged version? Let me know if you need help.

**Comment by gibertgibs** [comment]
The actual info is the one in my profile, this was just a demo to help the rest of the members get the point and purpose of the repository.

**Comment by MartinSchott** [comment]
okay thank you! Then I will close this issue.
