### ISSUE TITLE
Andrew Wafela.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#22]
![400186300161_1886](https://user-images.githubusercontent.com/71114711/114079510-f495f100-98b2-11eb-8968-3af8b14d8aa9.jpg)

Hello world! Call me Andrew ,Ugandan by nationality aged 34,an open source technician,earger to learn new methodologies  in tech.people call me in 
my home town "DOCTOR DEVICE. 
    I started my tech 20 years ago but I was all along doing my things offline without documentation.
     It was in 2019,when I came across  Mr vuga William ,the executive director of youth empowerment foundation (YEF) who introduced me to #ASKotec and we carried some innovations like building led light by Mr Maliamungu Richard of rhino camp,it was so interesting as i was already familiar with materials like transistors,resistor,capacitors ,diodes etc.
     A big boom was in late 2019 when we had a very big community repair cafe in adjumani at ruyo guest house ,here I was able to meet experts in open
 tech from Sudan,Kenya and Berlin germany,led by Mr timm wille who so interesting and inspiring.
     
Here was my time to know #ASKnet  and later got alink to trackII 2020/2021 where we collaborated on a lot of projects and github documentation. the online collaboration offered by #ASKnet has helped me a great deal because now am able to collaborate on any issue with distant people and am also able to publish my work for views by other experts. 
      Not only that,through #ASKnet  I had an opportunity to learn podcasting and audio editing by Mr Romeo ronald of platform africa,so as per now i can record my voice and do editing using an open source software audacity.
  My contuinity with #ASKnet is going to make me a job maker not a job seeker.
    Conclusively #ASKnet has come to clear an ending complains of an employment among youths across the world.
 
"JOIN #ASKnet TO BECOME AJOB MAKER NOT A JOB SEEKER"

**Comment by chardso** [comment]
![Uploading IMG_20210403_102148.jpg…]()

**Comment by gibertgibs** [comment]
Perfect... Let's keep going

**Comment by chardso** [comment]
![Uploading 400094600319_459934.jpg…]()

**Comment by bmen** [comment]
Content taken over to: http://0.0.0.0:4000/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Wafela-Andrew/
