### ISSUE TITLE
Timm Wille.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#26]

**Comment by gibertgibs** [comment]
---
title:  "Timm Wille"
metadate: "hide"
categories: [ Mentor, Github ]
image: "/assets/images/timm.jpg"
---

# Hello World! You can call me `Timm`
<p align="center">
<img src="../assets/images/timm.jpg" width=300>
</p>

I am an Open Source Hardware and Circular Economy activist and renewable engergy engineer from Berlin, Germany. 

Sharing knowledge and hands-on skills on #OpenTech  and sustainable transformation is my mission and passion since 2013 when I joined the Open Source Ecology movement. 

Runinng events, talks, workshops and founding initiatives as well as working in the field in South Sudan and Uganda led me to become a trainer and organizer for Open Source Ecology Germany and beyond. 

I started to research and develope methodes for Open Process Documentation and toolboxes like #ASKotec (Access to Skills and Knowledge open tech emergency case) to shape an innovative and #sustainable future on a global scale. 

**I see sharing knowledge as a form of true democracy and empowerment for the future solutions we need.**


---
>If you would like to connect or read more in detail you can choose here:
>- [Open Source Ecology Germany Profile | German](https://wiki.opensourceecology.de/Timm_Wille)
>- [Open Source Ecology Germany Profile | English](https://wiki.opensourceecology.de/En:Timm_Wille)

**Comment by MartinSchott** [comment]
@bmen there is a formatting issue with the links on the bottom of Timms profile that I can't figure out
file: https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/blob/Pintereso-Theme/_posts/2020-07-02-Timm-Wille.md
page where error occurs: https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Timm-Wille/

**Comment by MartinSchott** [comment]
I think the problem is the | character in the link text
