### ISSUE TITLE
Stephen Kovats.md

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#44]

**Comment by MartinSchott** [comment]
@timmwille please add his content (bio) from website
https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/edit/Pintereso-Theme/_posts/2020-07-10-Stephen-Kovats.md

**Comment by bmen** [comment]
https://github.com/ASKnet-Community/LEAD/issues/2
