### ISSUE TITLE
Revise tags and use only locations/regions

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#47]

**Comment by timmwille** [comment]
@maliarich shall we add all regions to the profiles? can you help?

**Comment by maliarich** [comment]
Hi timm

Yeah, and it's a great idea

**Comment by maliarich** [comment]
Yeah but the question is, a region link or simply writing a name of the region?

**Comment by MartinSchott** [comment]
discussion continues in new fork here: https://github.com/ASKnet-Community/LEAD/issues/1
