### ISSUE TITLE
Create your Story Basti

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#8]
@bmen create your Story https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/blob/Pintereso-Theme/_posts/2020-07-07-Sebastian.md

**Comment by timmwille** [comment]
change file name

**Comment by bmen** [comment]
@timmwille it's finished: https://asknet-open-training.github.io/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/Bastian-Menningen/
