### ISSUE TITLE
change web preview meta data

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021#9]
can we change the Metadata to have an other Social Preview @bmen ?
https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021/tree/Pintereso-Theme

![grafik](https://user-images.githubusercontent.com/8081055/111009832-f8f2eb00-8394-11eb-937c-fb2a18a302a0.png)

**Comment by bmen** [comment]
hmmm i changed it. Could you try it again?
